In [30]:
# EXERCICE 1

start_num = int(2000)
  
end_num = int(3200)

cnt = start_num
  
while cnt <= end_num:
    
    if cnt % 7 == 0 and cnt % 5!=0:
        print(cnt, " est divisible par 7 et non multiple de 5.")

    cnt += 1

2002  est divisible par 7 et non multiple de 5.
2009  est divisible par 7 et non multiple de 5.
2016  est divisible par 7 et non multiple de 5.
2023  est divisible par 7 et non multiple de 5.
2037  est divisible par 7 et non multiple de 5.
2044  est divisible par 7 et non multiple de 5.
2051  est divisible par 7 et non multiple de 5.
2058  est divisible par 7 et non multiple de 5.
2072  est divisible par 7 et non multiple de 5.
2079  est divisible par 7 et non multiple de 5.
2086  est divisible par 7 et non multiple de 5.
2093  est divisible par 7 et non multiple de 5.
2107  est divisible par 7 et non multiple de 5.
2114  est divisible par 7 et non multiple de 5.
2121  est divisible par 7 et non multiple de 5.
2128  est divisible par 7 et non multiple de 5.
2142  est divisible par 7 et non multiple de 5.
2149  est divisible par 7 et non multiple de 5.
2156  est divisible par 7 et non multiple de 5.
2163  est divisible par 7 et non multiple de 5.
2177  est divisible par 7 et non multipl

In [ ]:
# EXERCICE 2

nbr = int(input('Entrez un nombre : '))
fact = 1
for i in range(1, nbr+1):
    fact = fact * i

print (nbr,'! = ',fact)


In [55]:
# EXERCICE 5

import numpy as np
myArray = np.array([[0,1],[2,3],[4,5]])
# Convertit en liste 
myList = myArray.tolist()
print(myArray.tolist())

[[0, 1], [2, 3], [4, 5]]


In [61]:
# EXERCICE 6

import numpy as np
  
array1 = np.array([0, 1, 1])
array2 = np.array([2, 2, 1])
  
# Original array1
print(array1)
  
# Original array2
print(array2)
  
# Covariance matrix
print("\nCovariance matrix of the said arrays:\n",np.cov(array1, array2))


[0 1 1]
[2 2 1]

Covariance matrix of the said arrays:
 [[ 0.33333333 -0.16666667]
 [-0.16666667  0.33333333]]
